# Generated by Django 3.1.7 on 2022-07-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0011_auto_20210616_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='case_law',
            field=models.CharField(choices=[('Financial Law', 'Financial Law'), ('Education Law', 'Education Law'), ('Civil Law', 'Civil Law'), ('Property Law', 'Property Law'), ('Labour Law', 'Labour Law'), ('Healthcare Law', 'Healthcare Law'), ('Environment Law', 'Environment Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Social Law', 'Social Law'), ('Corruption Law', 'Corruption Law'), ('Criminal Law', 'Criminal Law'), ('Personal Law', 'Personal Law')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Financial Law', 'Financial Law'), ('Education Law', 'Education Law'), ('Civil Law', 'Civil Law'), ('Property Law', 'Property Law'), ('Labour Law', 'Labour Law'), ('Healthcare Law', 'Healthcare Law'), ('Environment Law', 'Environment Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Social Law', 'Social Law'), ('Corruption Law', 'Corruption Law'), ('Criminal Law', 'Criminal Law'), ('Personal Law', 'Personal Law')], default='1', max_length=100),
        ),
    ]
