# Generated by Django 3.1.7 on 2022-07-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0012_auto_20220728_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='case_law',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Civil Law', 'Civil Law'), ('Personal Law', 'Personal Law'), ('Education Law', 'Education Law'), ('Social Law', 'Social Law'), ('Corruption Law', 'Corruption Law'), ('Labour Law', 'Labour Law'), ('Environment Law', 'Environment Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Financial Law', 'Financial Law'), ('Property Law', 'Property Law'), ('Healthcare Law', 'Healthcare Law')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Criminal Law', 'Criminal Law'), ('Civil Law', 'Civil Law'), ('Personal Law', 'Personal Law'), ('Education Law', 'Education Law'), ('Social Law', 'Social Law'), ('Corruption Law', 'Corruption Law'), ('Labour Law', 'Labour Law'), ('Environment Law', 'Environment Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Financial Law', 'Financial Law'), ('Property Law', 'Property Law'), ('Healthcare Law', 'Healthcare Law')], default='1', max_length=100),
        ),
    ]
