# Generated by Django 3.1.5 on 2023-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0013_auto_20220728_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='case_law',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Environment Law', 'Environment Law'), ('Social Law', 'Social Law'), ('Healthcare Law', 'Healthcare Law'), ('Labour Law', 'Labour Law'), ('Personal Law', 'Personal Law'), ('Property Law', 'Property Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Civil Law', 'Civil Law'), ('Education Law', 'Education Law'), ('Corruption Law', 'Corruption Law'), ('Financial Law', 'Financial Law')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Criminal Law', 'Criminal Law'), ('Environment Law', 'Environment Law'), ('Social Law', 'Social Law'), ('Healthcare Law', 'Healthcare Law'), ('Labour Law', 'Labour Law'), ('Personal Law', 'Personal Law'), ('Property Law', 'Property Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Civil Law', 'Civil Law'), ('Education Law', 'Education Law'), ('Corruption Law', 'Corruption Law'), ('Financial Law', 'Financial Law')], default='1', max_length=100),
        ),
    ]
